### ISSUE TITLE
Bug when two emphasized words are next to each other

### ISSUE THREAD

**Issue by SPFabGerman** [awth13/org-appear#1]
When I have something like `*word1* *word2*` or `*word1* /word2/` or something similar, only the markers of the first word are toggled.

**Comment by awth13** [comment]
This was due to `org-emph-re` regular expression requiring special characters both _before_ and _after_ an emphasised fragment. Since there is only only space between consecutive words, the second word did not match. 

Fixed [in this commit](https://github.com/awth13/org-emphtog/commit/fae96f64f646d2d95613e4fcbcc831d20f52d72f) by making a custom regular expression that does not require special characters after an emphasised fragment, only before.
